apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-monitoring-kubernetes
subjects:
  - kind: ServiceAccount
    name: sa-cronjob-monitoring-kubernetes
    namespace: telegram-status
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-monitoring-kubernetes
