apiVersion: v1
kind: Pod
metadata:
  name: pod-com-erro
  namespace: telegram-status
spec:
  containers:
    - name: wordpress
      image: docker.io/bitnami/nao-existe-wordpress:6.1.1-debian-11-r67
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false